# Ejemplo para ejecutar una aplicación de python
FROM python:3.9-slim

# Establecer un directorio de trabajo
WORKDIR /aplicacion

# Copiar el fichero de Python:
COPY . .

# Ejecutar el comando:
CMD ["python", "codigo.py"]
