apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache    
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: volumen-apache

      volumes:
        - name: volumen-apache
          hostPath:
            path: /home/kubernetes/paginas
            type: Directory
