# Hacemos una actualización de la imagen de 1.26 a 1.27
# Y cambiamos la estrategia de Recreate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  Strategy:
    type: Recreate # Por defecto, es RollingUpdate
  selector:
    matchLabels:
      app: mi-app # Para buscar / agrupar con la misma label
  template:
    metadata:
      labels:
        app: mi-app # Le asigna a los pods y Replica set
    spec:
      containers:
        - name: mi-app-container
          image: nginx:1.27
          ports:
            - containerPort: 80
