apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-wordpress
  labels:
    app: wordpress

spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      app: wordpress
      tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
      name: wordpress
      env:
      - name: WORDPRESS_DB_HOST
        valueFrom:
          configMapKeyRef:
            name: wp-config
            key: WORDPRESS_DB_HOST
      - name: WORDPRESS_DB_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: wp-config
            key: WORDPRESS_DB_PASSWORD
      - name: WORDPRESS_DB_USER
        valueFrom:
          configMapKeyRef:
            name: wp-config
            key: WORDPRESS_DB_USER
      ports:
      - containerPort: 80
        name: wordpress
      volumeMounts:
      - name: vol2
        mountPath: /var/www/html
    volumes:
    - name: vol2
      persistentVolumeClaim:
        claimName: wp-pv-claim
