apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


