
services:
  service1:
    build:
      context: ./service1
    container_name: service1
    ports:
      - 5000
    networks:
      - flask-network

  service2:
    build: 
      context: ./service2
    container_name: service2
    ports:
      - 5001:5001
    networks:
      - flask-network

networks:
  flask-network:    

# docker network create flask-network