apiVersion: v1
kind: Pod
metadata:
  name: pod-volumen1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # Carpeta del contenedor en el POD
    - mountPath: /home
      name: home 
    - mountPath: /temp
      name: temp
  volumes:
  - name: home
    hostPath: # Carpeta dentro del nodo de minikube
      path: /home/kubernetes/datos 
  - name: temp
    emptyDir: {}
